### ISSUE TITLE
Missing functions

### ISSUE THREAD

**Issue by Selim042** [CoderPuppy/cc-emu#1]
OS API
- [x] day
- [x] getComputerID
- [x] getComputerLabel
- [x] setComputerLabel

**Comment by CoderPuppy** [comment]
I think id and label will require a config file (or folder).
What do you think of this?

```
└── .termu
    ├── id
    └── label
```

**Comment by Selim042** [comment]
Looks good to me ;P

**Comment by CoderPuppy** [comment]
What do you think `os.day` should return?
Days since UNIX epoch?
Or should it be closer to CC and increment every 20 minutes?
Or something else?

**Comment by Selim042** [comment]
I would say similar to CC as some programs might fail to make sense if it isn't similar.  I would possibly just have it start at 1 when the emulator starts and, if easily possible, track the day from there.  If not, reset 1 each time the emulator starts.

**Comment by CoderPuppy** [comment]
Ok, all done!
If you find anything more missing, reopen this or create a new issue.

**Comment by Selim042** [comment]
Great!
