### ISSUE TITLE
BIOS Error

### ISSUE THREAD

**Issue by Selim042** [CoderPuppy/cc-emu#3]
`bios.lua:496: bad argument #1 to 'load' (function expected, got nil)`
Occurs on boot if startup contains os.loadAPI.
Attempting to run startup after error occurs returns:

```
API . is already being loaded
bios.lua:496: bad argument #1 to 'load' (function expected, got nil)
```

If it makes a difference, I am using the rpi-gpio branch.

**Comment by CoderPuppy** [comment]
09d0df2 should have fixed this, but I'll reopen this pending confirmation that it works.

**Comment by Selim042** [comment]
Still got `bios.lua:496: bad argument #1 to 'load' (function expected, got nil)`

**Comment by CoderPuppy** [comment]
I'd forgotten to push  the changes to `rpi-gpio`, it should work now.
If that wasn't on `rpi-gpio` then what CC version are you using?

**Comment by Selim042** [comment]
Well, that doesn't make a difference as I just downloaded the modified file and copied it myself.  The changed file was used and did not work.  Using the latest files from [alekso56/ComputercraftLua](http://github.com/alekso56/ComputercraftLua)

**Comment by CoderPuppy** [comment]
What code are you running?

**Comment by Selim042** [comment]
```
local file = fs.list("/apis/")
for k,v in pairs(file) do
  os.loadAPI("/apis/"..v)
end
```

EDIT: Nevermind, I think I found the issue.  Give me a minute.

**Comment by CoderPuppy** [comment]
Could you post `libs/fs.lua`?

**Comment by Selim042** [comment]
I didn't find the issue :(
fs.lua: http://pastebin.com/qnXiszKH

**Comment by CoderPuppy** [comment]
Could you figure out what file it's trying to load (add a print in the loop)?

**Comment by Selim042** [comment]
`.`
fs.list still returns both `.` and `..`  for some reason.

**Comment by CoderPuppy** [comment]
Could you post `emu.lua`?
I have a hunch that you have an old `emu.lua` that has `fs` builtin instead of loading `libs/fs.lua`.

**Comment by Selim042** [comment]
I did just re-download the entire branch when I realized that it was still returning `.`, but here it is: http://pastebin.com/rBQt920W

**Comment by CoderPuppy** [comment]
Ok, my hunch was wrong.
Could you run `fs.list('/apis')` in `lua` and post the output?

Also could just make sure you're running this version, not some other copy you might have, because this shouldn't happen at all (at least not with a somewhat recent version).

**Comment by Selim042** [comment]
```
{
  ".",
  "..",
  "cleverbot",
}
```

I just redownloaded the branch.

**Comment by CoderPuppy** [comment]
[That shouldn't happen.](https://github.com/CoderPuppy/cc-emu/blob/rpi-gpio/libs/fs.lua#L91)

**Comment by Selim042** [comment]
WTF.  Went to record my screen showing that the lines that should prevent it are in fs.lua, went to run fs.list, didn't show it anymore.  No clue as to why, launched it the same way I normally do, same directory, etc.  Nothing changed, but it works properly now.
