### ISSUE TITLE
fs.delete

### ISSUE THREAD

**Issue by Selim042** [CoderPuppy/cc-emu#4]
Ok, this one should be a real issue, unlike my previous one:

```
lua> fs.list("apis")
{
  "cleverbot",
}
lua> fs.delete("apis/cleverbot")    
lua> fs.list("apis")            
{
  "cleverbot",
}
```

`fs.delete` does not seem to work as intended if within a directory or the target is a directory.

**Comment by CoderPuppy** [comment]
It works for me.
I just added error handling to `fs.delete` so try with the new version and there should be an error.

**Comment by Selim042** [comment]
I have a permission denied.
I think I may have added the file from outside Termu then and had improper permissions for Termu to manage the file.  Darn, I thought I did better this time.
