### ISSUE TITLE
dofile missing

### ISSUE THREAD

**Issue by Selim042** [CoderPuppy/cc-emu#6]
`_G.dofile` is also missing.

**Comment by CoderPuppy** [comment]
Not a bug, `dofile` was [removed](https://github.com/alekso56/ComputercraftLua/commit/1530ec1c49489750b35b2b76c6740ef9d8e61eb5#diff-005569a26b4cee4ae76746e32d181ec0L402) from CC as of 1.74pr20.

**Comment by Selim042** [comment]
Oh.  Nevermind then.
