### ISSUE TITLE
Not working at all, drops a ton of "no file" errors

### ISSUE THREAD

**Issue by liquidev** [CoderPuppy/cc-emu#7]
For whatever reason this emulator does not even start at all. This is what it shows:

```
lua5.2: cli.lua:5: module 'pl.path' not found:
	no field package.preload['pl.path']
	no file '/usr/local/share/lua/5.2/pl/path.lua'
	no file '/usr/local/share/lua/5.2/pl/path/init.lua'
	no file '/usr/local/lib/lua/5.2/pl/path.lua'
	no file '/usr/local/lib/lua/5.2/pl/path/init.lua'
	no file '/usr/share/lua/5.2/pl/path.lua'
	no file '/usr/share/lua/5.2/pl/path/init.lua'
	no file './pl/path.lua'
	no file '/usr/local/lib/lua/5.2/pl/path.so'
	no file '/usr/lib/arm-linux-gnueabihf/lua/5.2/pl/path.so'
	no file '/usr/lib/lua/5.2/pl/path.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './pl/path.so'
	no file '/usr/local/lib/lua/5.2/pl.so'
	no file '/usr/lib/arm-linux-gnueabihf/lua/5.2/pl.so'
	no file '/usr/lib/lua/5.2/pl.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './pl.so'
stack traceback:
	[C]: in function 'require'
	cli.lua:5: in main chunk
	[C]: in ?
```

I don't understand why this happens to me. I have installed all the dependencies. I am running Ubuntu MATE 16.04 LTS on a Raspberry Pi 3 Model B+.

**Comment by CoderPuppy** [comment]
How did you install the dependencies?

**Comment by liquidev** [comment]
I installed them using LuaRocks. From what I researched I have done something wrong when installing Penlight, and instead for Lua 5.2 it installed for Lua 5.1. So how do I fix that?

**Comment by CoderPuppy** [comment]
How did you install LuaRocks? The Ubuntu 16.04 repos only have LuaRocks for Lua 5.1 so you'll have to [install it manually](https://github.com/luarocks/luarocks/wiki/Download).

**Comment by liquidev** [comment]
OK, now I fixed Penlight and stuff, but this happens:

```
1	false	@
2	false	./emu.lua:264: @
3	false	libs/input.lua:112: @
4	false	./emu.lua:132: @
error
libs/input.lua:112: attempt to call field 'key_backspace' (a nil value)
Segmentation fault (core dumped)
```

Why? Also previously it searched for `terminfo-norm` but this rock doesn't exist, so I replaced it with `terminfo` in the code.

**Comment by liquidev** [comment]
Nevermind, I already fixed that. I was missing some files in the root directory. Anyways, thanks for help.
